### ISSUE TITLE
Using fSpy programmatically 

### ISSUE THREAD

**Issue by TalTaiber** [stuffmatic/fSpy#115]
First off, thank you for your brilliant work!

Say I have a computer vision program (in python) that finds the 2 sets of vanishing point lines, and chooses a 3D origin point. I want to pass that information programatically to fSpy, and then get back the inferred camera extrinsics and focal length. How can I go about doing this? Do I have to use TypeScript? What is the correct format to specify the lines and origin point? 

Cheers

**Comment by stuffmatic** [comment]
There is actually an undocumented command line interface that lets you do just that. You should be able to see supported parameters etc in [the CLI source](https://github.com/stuffmatic/fSpy/blob/develop/src/cli/cli.ts) (especially `printUsage`).
