### ISSUE TITLE
how to install fspy add on in Mac blender ?

### ISSUE THREAD

**Issue by thirdpoler** [stuffmatic/fSpy#16]
I don't know how to import fspy add on in blender on Mac and also can I use fspy in blender 2.79?

**Comment by MWDUSER7** [comment]
I can't install the Blender add on into 2.8. It doesn't show up in the Import menu? I have watched the tutorials I=on how to install and it just doesn't seem to work??

**Comment by stuffmatic** [comment]
Annoyingly, Safari unzips downloaded zip files by default. If you downloaded the add-on with Safari, you'll have to manually compress the downloaded add-on folder and point Blender to the resulting zip file when installing the add-on. 

I've added a section to the readme about this 
https://github.com/stuffmatic/fSpy-Blender/blob/master/README.md

**Comment by stuffmatic** [comment]
If you're still having problems with this, please open an issue in the importer issue tracker https://github.com/stuffmatic/fSpy-Blender/issues

**Comment by ozkrd60** [comment]
Hello i have a big problem. First, i think the zip doesn't work because i'm on mac Air M1, and secondly, Blender cannot find this extension. Help me please i really wanted to use Fspy. Thousand thanks to you !!
