### ISSUE TITLE
How does the Camera Parameter Data relate to the  Axis Angle values in the Gui?

### ISSUE THREAD

**Issue by phillvancejr** [stuffmatic/fSpy#18]
I'm trying to work with the json/binary camera parameter data and I've noticed that none of the numbers in the json file seem to line up with the values in the gui.  I'm assuming some sort of conversion is happening. If I have everything set to degrees, how do I convert the json/binary camera parameters into the numbers I see in the gui?

**Comment by stuffmatic** [comment]
Angle values, e.g field of view, are stored in radians and can be converted to degrees like so:

```
angleInDegrees = angleInRadians * 57.29577951308232 // Multiply by 180 / PI
```
