### ISSUE TITLE
Reference distance issues

### ISSUE THREAD

**Issue by symo470** [stuffmatic/fSpy#20]
I am having difficulty with the Reference distance in fSpy.

The input box where you would type the variable (default 4) does not accept input. The drop down next to it allows you to select the unit as expected (Meters, Millimeters, Inches etc), but not the input box. 

I am likely doing something wrong as I would assume that this would have been picked up as an issue prior to this.

In my example, I know the size/width of the Evacuation Diagram (315mm) , and am hoping to scale the entire scene so when in Blender, I can import scaled models without having to adjust by eye.

Anyone else having this issue?

![Example](https://user-images.githubusercontent.com/53155659/61598490-fabce780-ac61-11e9-8c4e-42a29065bf20.JPG)

**Comment by stuffmatic** [comment]
Stupid question maybe, but did you press return after entering the value? If you don't, the value you entered won't be set.

**Comment by symo470** [comment]
I did say that I was likely doing something wrong! 😳
I was tabbing out of the input box!
Sorry for wasting your time.

**Comment by foreachthing** [comment]
> 
> 
> I was tabbing out of the input box!

I, too, tab out of everything ... no wonder it didn't work.

**Comment by marksteward** [comment]
This is super confusing and unlike any other Windows UI. Would you accept a patch to fix it?
