### ISSUE TITLE
I cant make z axis straight up

### ISSUE THREAD

**Issue by MSCreationAndMore** [stuffmatic/fSpy#24]
Hello Stuffmatic

i want to use fspy for furniture modeling every thing is correct except z axis i cant make it straight even if i choose manual principal point , regular if i draw with one/two vanishing point i can make any straight line in z axis 
![Capture02](https://user-images.githubusercontent.com/36688285/65259037-483fbe80-db04-11e9-9766-31b00f99daeb.JPG)
![Capture01](https://user-images.githubusercontent.com/36688285/65259040-483fbe80-db04-11e9-8c04-90c85f681e70.JPG)

**Comment by stuffmatic** [comment]
Possible clues: If the image has been asymmetrically cropped, two vanishing points will not be enough to compute the camera parameters. Also, it seems the y axis vanishing point lines are near-parallel, which may lead to inaccurate results.
