### ISSUE TITLE
How do you install fspy on to blender

### ISSUE THREAD

**Issue by MathMusicMystery** [stuffmatic/fSpy#25]
I've tried to install using the install button on preferences, but when I select fspy it won't install

**Comment by stuffmatic** [comment]
For step-by-step installation instructions, have a look at https://github.com/stuffmatic/fSpy-Blender#getting-started

**Comment by Dedas** [comment]
I have the same problem. Followed the instructions.

**Comment by stuffmatic** [comment]
If you're still having problems with this, please open an issue in the importer issue tracker https://github.com/stuffmatic/fSpy-Blender/issues
