### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by paperbenni** [stuffmatic/fSpy#3]
When I try to start the AppImage on Ubuntu 18.10 it says Segmentation fault (core dumped) in the terminal and then quits. App Images are supposed to be portable so I don't know if that's a distro-wide problem but it certainly does make the program unusable. Google tells me that it's probably a bug so I hope you'll be able to fix it. I would love to use this program, it seems pretty cool. Thanks in advance ;)

**Comment by stuffmatic** [comment]
Reported by another user (seems to be the same issue):
<img width="664" alt="screen shot 2018-11-16 at 07 35 42" src="https://user-images.githubusercontent.com/2444852/48602122-5ec03b00-e972-11e8-936f-a26f68f43996.png">

**Comment by stuffmatic** [comment]
@paperbenni Thanks for the report. I've published a new version with a potential fix for this issue. Let me know how you go.

**Comment by paperbenni** [comment]
Yup, it works now. Thanks!
