### ISSUE TITLE
Multiple Versions Installed - Can't tell which is running

### ISSUE THREAD

**Issue by jjfeenix** [stuffmatic/fSpy#30]
Love this tool!

I have fSpy versions 1.0.2 & 1.0.3 installed on Win10. Still using Blender 2.79, as well as 2.80.

They look identical when started. Is there a way to **_quickly_** tell which version I'm using? 

I can't find an About dialog or version number anywhere in the interface.

**Comment by stuffmatic** [comment]
The add-on version number is show in the add-ons list.

<img width="657" alt="Screenshot 2019-11-16 at 14 46 29" src="https://user-images.githubusercontent.com/2444852/68994200-95c87580-0880-11ea-938d-cd919b0c3f16.png">

**Comment by jjfeenix** [comment]
Per:

I was referring to the fSpy application version. 
1. It would be nice to see what the version is somewhere in the app interface.

2. Am I wrong in thinking that the fSpy App and Blender Add-on versions have to match? 
Example: 
App version 1.0.2 + Blender add-on ver. 1.0.2 for Blender 2.79 ONLY.  
App version 1.0.3 + Blender add-on ver. 1.0.3 for Blender 2.80 ONLY.

3. Is there someplace dedicated to asking questions and conversing with other users, besides here?

Thanks for the quick reply.

**Comment by stuffmatic** [comment]
> I was referring to the fSpy application version.

Ah sorry. 

> It would be nice to see what the version is somewhere in the app interface.

The fSpy version is shown in the top right corner of the start screen. Can't remember which version this was added in though. Older versions might not show the version number, but you should be able to distinguish between 1.0.3 and older versions at the very least.

<img width="938" alt="Screenshot 2019-11-16 at 19 30 07" src="https://user-images.githubusercontent.com/2444852/68997497-988a9100-08a7-11ea-9f19-df9733781ffc.png">

> Am I wrong in thinking that the fSpy App and Blender Add-on versions have to match?

Yes, you would be wrong :) The version numbers just happen to match. The different add-on versions can all import fSpy project files from any version of fSpy.

> Is there someplace dedicated to asking questions and conversing with other users, besides here?

There's no dedicated fSpy user forum, but you might want have a look at the [Blender Artists forum](https://blenderartists.org). Also, there seems to be some fSpy related activity on [Blender Stack Exchange](https://blender.stackexchange.com/search?q=fspy).

**Comment by jjfeenix** [comment]
> The fSpy version is shown in the top right corner of the start screen.

Ahhh, that's exactly what I was looking for. Just a little a little more contrast with the background would help my tired old eyes.

> The version numbers just happen to match. The different add-on versions can all import fSpy project files from any version of fSpy.

OK, I get it now.

> There's no dedicated fSpy user forum, but you might want have a look at the Blender Artists forum. Also, there seems to be some fSpy related activity on Blender Stack Exchange.

BA was where I first learned of fSpy. Will check it out BSE.

Thanks again!
