### ISSUE TITLE
Build for macOS is supported only on macOS?

### ISSUE THREAD

**Issue by Shaun-Fong** [stuffmatic/fSpy#31]
hi , This means that I can only build on mac platform?
Im windows user

**Comment by stuffmatic** [comment]
If you just want do download and run the app, get the latest windows binary from the [downloads section](https://github.com/stuffmatic/fSpy/releases).

I use macOS for development and for building binaries for all platforms. I've never tried to get the build to run on windows. It should be possible, but will likely require some tweaking.

**Comment by Shaun-Fong** [comment]
okay , thanks

**Comment by Shaun-Fong** [comment]
oh @stuffmatic 
remove "DEV=true" in package.json line 62
run successed
