### ISSUE TITLE
Just a questin about the software

### ISSUE THREAD

**Issue by Ladvace** [stuffmatic/fSpy#32]
Did you use some third part library for the "3d" part of the software, I mean vanish point, 3d axis...?

**Comment by stuffmatic** [comment]
No 3rd party library was used for the solver math stuff. Here's the solver code if you're curious https://github.com/stuffmatic/fSpy/tree/develop/src/gui/solver

**Comment by Ladvace** [comment]
oh thanks, did you also made from scratch the "graphic" part?

**Comment by stuffmatic** [comment]
I'm using [react-konva](https://github.com/konvajs/react-konva) to draw everything that's on top of the image. This library makes it easy to draw primitives like lines, circles etc. The "3D graphics" in fSpy is just a bunch of lines drawn using react-konva.

**Comment by Ladvace** [comment]
well, good job and thank you
