### ISSUE TITLE
How to download Fspy Application for Mac

### ISSUE THREAD

**Issue by sanzacarria** [stuffmatic/fSpy#51]
Hi I've been trying to download the application for Mac and I can't seem to find the separate application in the zip files. I've gotten the blender addon to work and it imports the test files fine. Is there a special way to import the app to mac?

**Comment by stuffmatic** [comment]
Download [fSpy-1.0.3.dmg](https://github.com/stuffmatic/fSpy/releases/download/v1.0.3/fSpy-1.0.3.dmg) (from [here](https://github.com/stuffmatic/fSpy/releases/tag/v1.0.3)).
