### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by paperbenni** [stuffmatic/fSpy#6]
Feature request:
It would be really cool if you would be able to zoom in. 
It would just make things a lot easier.

**Comment by SteffenDuenner** [comment]
Have you tried pressing SHIFT while moving points?

**Comment by paperbenni** [comment]
Yes, i know about that, feels pretty at home coming from blender ;)
But zooming in could still come in handy and is actually more useful in some scenarios.

**Comment by Lookahs** [comment]
The 'shift' function is definitely useful, however a zoom in itself would also be very useful.

Here's a scenario.
I have a gable end of a building that is built in brick. I would like to set one of the lines along a mortar joint line. With the 'shift' function, I can set one end of the line correctly on the mortar joint. But I am unable to see whether from one end of the building to the other end - the line actually follows the same mortar line and doesn't accidentally jump one brick higher or lower.

Having zoom, would allow me to make sure the line is placed correctly.
